// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const env = import.meta.env as Record<string, string | undefined>;

// Support both manual .env and Lovable's automated Supabase (injects URL + anon key when Supabase is connected)
const SUPABASE_URL = env.VITE_SUPABASE_URL ?? env.SUPABASE_URL ?? "";
const SUPABASE_KEY =
  env.VITE_SUPABASE_PUBLISHABLE_KEY ??
  env.VITE_SUPABASE_ANON_KEY ??
  env.SUPABASE_ANON_KEY ??
  "";

/** True if Supabase is configured (works with Lovable auto-setup or manual .env) */
export const isSupabaseConfigured = Boolean(
  SUPABASE_URL && SUPABASE_KEY && !SUPABASE_URL.includes("placeholder") && SUPABASE_KEY !== "placeholder"
);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL || "https://placeholder.supabase.co", SUPABASE_KEY || "placeholder", {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});