// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const env = import.meta.env as Record<string, string | undefined>;

// Lovable: injects VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY when Supabase is connected. Local dev: same var names in .env.
const SUPABASE_URL = env.VITE_SUPABASE_URL ?? env.SUPABASE_URL ?? "";
const SUPABASE_KEY =
  env.VITE_SUPABASE_PUBLISHABLE_KEY ??
  env.VITE_SUPABASE_ANON_KEY ??
  env.SUPABASE_ANON_KEY ??
  "";

const configured = Boolean(
  SUPABASE_URL && SUPABASE_KEY && !SUPABASE_URL.includes("placeholder") && SUPABASE_KEY !== "placeholder"
);

// #region agent log
fetch('http://127.0.0.1:7932/ingest/c42627de-8b23-4aa5-8010-342238c3f680',{method:'POST',headers:{'Content-Type':'application/json','X-Debug-Session-Id':'da479d'},body:JSON.stringify({sessionId:'da479d',location:'client.ts:init',message:'Supabase client init',data:{hasUrl:Boolean(SUPABASE_URL),hasKey:Boolean(SUPABASE_KEY),isConfigured:configured},timestamp:Date.now(),runId:'run1',hypothesisId:'A'})}).catch(()=>{});
// #endregion

let _client: ReturnType<typeof createClient<Database>>;
let _isConfigured: boolean;
try {
  // #region agent log
  fetch('http://127.0.0.1:7932/ingest/c42627de-8b23-4aa5-8010-342238c3f680',{method:'POST',headers:{'Content-Type':'application/json','X-Debug-Session-Id':'da479d'},body:JSON.stringify({sessionId:'da479d',location:'client.ts:createClient',message:'Before createClient',data:{},timestamp:Date.now(),runId:'run1',hypothesisId:'A'})}).catch(()=>{});
  // #endregion
  _client = createClient<Database>(
    SUPABASE_URL || "https://placeholder.supabase.co",
    SUPABASE_KEY || "placeholder",
    {
      auth: {
        storage: (typeof localStorage !== "undefined" ? localStorage : { getItem: () => null, setItem: () => {}, removeItem: () => {} }) as Storage,
        persistSession: true,
        autoRefreshToken: true,
      },
    }
  );
  _isConfigured = configured;
  // #region agent log
  fetch('http://127.0.0.1:7932/ingest/c42627de-8b23-4aa5-8010-342238c3f680',{method:'POST',headers:{'Content-Type':'application/json','X-Debug-Session-Id':'da479d'},body:JSON.stringify({sessionId:'da479d',location:'client.ts:afterCreate',message:'After createClient',data:{},timestamp:Date.now(),runId:'run1',hypothesisId:'A'})}).catch(()=>{});
  // #endregion
} catch (e) {
  _client = createClient<Database>("https://placeholder.supabase.co", "placeholder", {
    auth: { persistSession: false, autoRefreshToken: false },
  });
  _isConfigured = false;
}

/** True if Supabase is configured (Lovable injects these when Supabase is connected) */
export const isSupabaseConfigured = _isConfigured;
export const supabase = _client;